service: repairs-listener
provider:
  name: aws
  runtime: dotnet6
  memorySize: 2048
  vpc: ${self:custom.vpc.${opt:stage}}
  stage: ${opt:stage}
  region: eu-west-2
  timeout: 15
  usagePlan:
    - secureAccess:
        throttle:
          burstLimit: 200
          rateLimit: 100
  tracing:
    lambda: true
  versionFunctions: false

package:
  artifact: ./bin/release/net6.0/repairs-listener.zip

functions:
  RepairsListener:
    name: ${self:service}-${self:provider.stage}
    handler: RepairsListener::RepairsListener.SqsFunction::FunctionHandler
    role: lambdaExecutionRole
    environment:
      ### Re-use the same parameter as used by web api applications
      ENVIRONMENT:  ${ssm:/housing-tl/${self:provider.stage}/aspnetcore-environment}
      REPAIRS_DB_CONNECTION_STRING: Host=${ssm:/repairs-api/${self:provider.stage}/postgres-hostname};Port=${ssm:/repairs-api/${self:provider.stage}/postgres-port};Database=${ssm:/repairs-api/${self:provider.stage}/postgres-database};Username=${ssm:/repairs-api/${self:provider.stage}/postgres-username};Password=${ssm:/repairs-api/${self:provider.stage}/postgres-password}
    events:
      ### Specify the parameter containing the queue arn used to trigget the lambda function here
      ### This will have been defined in the terraform configuration
       - sqs: ${ssm:/sqs-queue/${self:provider.stage}/repairshubinbound/arn}

resources:
  Resources:
    lambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /${self:service}/${self:provider.stage}/
        RoleName: ${self:service}-lambdaExecutionRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
          - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
        Policies:
          - PolicyName: manageLogs
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'log-group:/aws/lambda/*:*:*'
                - Effect: "Allow"
                  Action:
                    - "s3:PutObject"
                    - "s3:GetObject"
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:s3:::"
                        - "Ref": "ServerlessDeploymentBucket"
          - PolicyName: lambdaInvocation
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "lambda:InvokeFunction"
                  Resource: "*"
          - PolicyName: sqsAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "sqs:ChangeMessageVisibility"
                    - "sqs:DeleteMessage"
                    - "sqs:GetQueueAttributes"
                    - "sqs:GetQueueUrl"
                    - "sqs:ListQueueTags"
                    - "sqs:ReceiveMessage"
                    - "sqs:SendMessage"
                    - "kms:Decrypt"
                  Resource: "*"

custom:
  vpc:
    development:
      securityGroupIds:
        - sg-08e28776da7918e4b
      subnetIds:
        - subnet-0140d06fb84fdb547
        - subnet-05ce390ba88c42bfd
    staging:
      securityGroupIds:
        - sg-011122be56aa0af9e
      subnetIds:
        - subnet-06d3de1bd9181b0d7
        - subnet-0ed7d7713d1127656
    production:
      securityGroupIds:
        - sg-0ec487b8798809285
      subnetIds:
        - subnet-0beb266003a56ca82
        - subnet-06a697d86a9b6ed01
