version: 2.1

orbs:
  node: circleci/node@6.3.0
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  docker-python:
    docker:
      - image: circleci/python:3.7
  docker-terraform:
    docker:
      - image: "hashicorp/terraform:light"
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws

  terraform-init-then-apply:
    description: "Initializes and applies terraform configuration"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform get -update=true
            terraform init
            terraform plan
          name: get, init and plan
      - run:
          name: apply
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform apply -auto-approve

  deploy-lambda:
    description: "Deploys via Serverless"
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - node/install
      - run:
          name: Install serverless CLI
          command: npm i -g serverless
      - run:
          name: Build lambda
          command: |
            cd ./RepairsListener/
            chmod +x ./build.sh
            ./build.sh
      - run:
          name: Deploy lambda
          command: |
            cd ./RepairsListener/
            npx --yes serverless deploy --stage <<parameters.stage>> --conceal

  terraform-init-then-destroy:
    description: "Initializes and destroys terraform configuration"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform get -update=true
            terraform init
          name: get and init
      - run:
          name: destroy
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform destroy -auto-approve

  remove-lambda:
    description: "Removes via Serverless"
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - node/install
      - run:
          name: Install serverless CLI
          command: npm i -g serverless@"<3.0.0"
      - run:
          name: Remove lambda
          command: |
            cd ./BonusCalcListener/
            npx --yes serverless remove --stage <<parameters.stage>> --conceal

jobs:
  assume-role-dr:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_DISASTER_RECOVERY

  terraform-init-and-apply-to-dr:
    executor: docker-terraform
    steps:
      - terraform-init-then-apply:
          environment: "production"

  deploy-to-dr:
    executor: docker-dotnet
    steps:
      - deploy-lambda:
          stage: "production"

  remove-from-disaster-recovery:
    executor: docker-dotnet
    steps:
      - remove-lambda:
          stage: "production"

  terraform-init-and-destroy-dr:
    executor: docker-terraform
    steps:
      - terraform-init-then-destroy:
          environment: "production"

workflows:
  # check-and-deploy-dr:
  #   jobs:
  #     - assume-role-dr:
  #         context: api-assume-role-disaster-recovery-context
  #     - terraform-init-and-apply-to-dr:
  #         requires:
  #           - assume-role-dr
  #     - deploy-to-dr:
  #         context:
  #           - "Serverless Framework"
  #           - api-nuget-token-context
  #         requires:
  #           - terraform-init-and-apply-to-dr

  cleanup-dr-infrastructure:
    jobs:
      - assume-role-dr:
          context: api-assume-role-disaster-recovery-context
      - remove-from-disaster-recovery:
          requires:
            - assume-role-dr
      - terraform-init-and-destroy-dr:
          requires:
            - remove-from-disaster-recovery